### ISSUE TITLE
'Game Starting' output

### ISSUE THREAD

**Issue by Derekholio** [ryanpetersonOF/DMT#16]
When no one is ready or when all players are spectators clicking 'Start Game' or 'Start Endless Game' logs 'Game Starting!' into the chat, rather than a message stating why a game can't be started at that instance.

**Comment by ryanpetersonOF** [comment]
I knew about this.  Its cause the game starts but then ends right away because no players. will look at fix

**Comment by ryanpetersonOF** [comment]
Fixed.  You now need 2 players to start a game.  I was purposely avoiding this but look what you made me do
